apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: smtp
spec:
  type: bindings.smtp
  version: v1
  metadata:
  - name: host
    value: localhost
  - name: port
    value: 1025
  - name: user
    value: ""
  - name: password
    value: ""
  - name: skipTLSVerify
    value: true
  - name: emailFrom
    value: "workflow@example.com"
  - name: emailFromName
    value: "Workflow System" 